name: build

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        gcc --version
        make test
    - uses: codecov/codecov-action@v2

  build_windows:
    runs-on: windows-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Build
      run: |
        gcc --version
        make build
        cp name_release.exe name_release_windows.exe
      shell: cmd
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: name_release_windows.exe
        path: name_release_windows.exe

  build_ubuntu:
    strategy:
      matrix:
        tag: [focal]
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        gcc --version
        make build
        cp name_release name_release_ubuntu_${{ matrix.tag }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: name_release_ubuntu_${{ matrix.tag }}
        path: name_release_ubuntu_${{ matrix.tag }}
